e_commerce_site/carts/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_decrease

app_name = "carts"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("decrease/<int:product_id>/", cart_decrease, name="cart_decrease"),
]

e_commerce_site/e_commerce_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls")),
    path("cart/", include("carts.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce_site/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("category/<slug:category_slug>/", views.product_list, name="category_filter"),
    path("<int:id>/<slug:product_slug>/", views.product_detail, name="product_detail"),
]

e_commerce_site/products/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator
# category model
class Category(models.Model):
    GENDER_CHOICES = [
        ("men", "Men"),
        ("women", "Women"),
        ("kids", "Kids"),
        ("unisex", "Unisex"),
    ]

    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to="categories/", blank=True)
    gender = models.CharField(
        max_length=10, choices=GENDER_CHOICES, default="unisex"
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:category_detail", args=[self.slug])
# Supplier model
class Supplier(models.Model):
    name = models.CharField(max_length=200)
    contact_email = models.EmailField(blank=True)
    phone = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
# Product model (DESIGN / DESCRIPTION ONLY)
class Product(models.Model):
    FABRIC_CHOICES = [
        ("cotton", "Cotton"),
        ("linen", "Linen"),
        ("silk", "Silk"),
        ("denim", "Denim"),
        ("chiffon", "Chiffon"),
        ("wool", "Wool"),
    ]

    SEASON_CHOICES = [
        ("summer", "Summer"),
        ("winter", "Winter"),
        ("all", "All Season"),
    ]

    OCCASION_CHOICES = [
        ("casual", "Casual"),
        ("formal", "Formal"),
        ("party", "Party"),
        ("wedding", "Wedding"),
        ("eid", "Eid"),
    ]

    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products"
    )
    supplier = models.ForeignKey(
        Supplier, on_delete=models.SET_NULL, null=True, blank=True
    )

    fabric = models.CharField(
        max_length=20, choices=FABRIC_CHOICES, blank=True
    )
    season = models.CharField(
        max_length=10, choices=SEASON_CHOICES, default="all"
    )
    occasion = models.CharField(
        max_length=20, choices=OCCASION_CHOICES, default="casual"
    )

    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={'id':self.id , 'slug':self.slug})

#PRODUCT VARIANT (THIS IS THE MOST IMPORTANT MODEL)
class ProductVariant(models.Model):
    SIZE_CHOICES = [
        ("xs", "XS"),
        ("s", "S"),
        ("m", "M"),
        ("l", "L"),
        ("xl", "XL"),
        ("xxl", "XXL"),
    ]

    COLOR_CHOICES = [
        ("white", "White"),
        ("black", "Black"),
        ("blue", "Blue"),
        ("red", "Red"),
        ("green", "Green"),
        ("gray", "Gray"),
    ]

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="variants"
    )

    size = models.CharField(max_length=10, choices=SIZE_CHOICES)
    color = models.CharField(max_length=20, choices=COLOR_CHOICES)

    sku = models.CharField(max_length=50, unique=True)

    price = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(0)]
    )
    compare_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    cost_price = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(0)]
    )

    stock = models.PositiveIntegerField(default=0)

    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("product", "size", "color")

    def __str__(self):
        return f"{self.product.name} - {self.color} - {self.size}"

    def in_stock(self):
        return self.stock > 0

    def discount_percentage(self):
        if self.compare_price and self.compare_price > self.price:
            return int(
                ((self.compare_price - self.price) / self.compare_price) * 100
            )
        return 0
# Product Image model
class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to="products",blank=True, null=True)
    alt_text = models.CharField(max_length=200, blank=True)
    is_primary = models.BooleanField(default=False)
    color = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f"Image for {self.product.name}"

e_commerce_site/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category


def product_list(request, category_slug=None):
    products = Product.objects.filter(is_active=True)
    category = None
    categories = Category.objects.filter(is_active=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(
        request,
        "products/product_list.html",
        {
            "category": category,
            "categories": categories,
            "products": products,
        },
    )


def product_detail(request, id, product_slug):
    product = get_object_or_404(
        Product,
        id=id,
        slug=product_slug,
        is_active=True
    )

    return render(
        request,
        "products/detail.html",
        {"product": product},
    )

e_commerce_site/products/templates/products/detail.html
{% extends "base.html" %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container mx-auto p-4 max-w-4xl">

  <!-- Product Name -->
  <h1 class="text-3xl font-bold mb-6">
    {{ product.name }}
  </h1>

  <!-- Product Image -->
  <div class="w-full mb-6">
    {% with product.images.first as image %}
      {% if image %}
        <img
          src="{{ image.image.url }}"
          alt="{{ product.name }}"
          class="h-64 w-44 object-cover rounded border"
        />
      {% endif %}

    {% endwith %}
  </div>

  <!-- Product Details -->
  <div class="space-y-4">

    <p class="text-gray-700">
      {{ product.description }}
    </p>

    {% with product.variants.first as variant %}
      {% if variant %}
        <p class="text-2xl  text-blue-600 font-semibold ">
          Rs {{ variant.price }}
        </p>
      {% else %}
        <p class="text-sm text-gray-500">
          Price not available
        </p>
      {% endif %}
    {% endwith %}
              <form action= "{% url 'carts:cart_add' product.id %}" method="post" id ="add-to-cart-form">
            {% csrf_token %}
            <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-4 rounded">
            Add to Cart
            </button>
            <p id="cart-message" class="text-green-600 mt-2 hidden">Item added to cart!</p>
          </form>

  </div>

</div>
<script>
document.getElementById("add-to-cart-form").addEventListener("submit", function(event) {
  event.preventDefault();

  const form = event.target;
  const url = form.action;
  const formData = new FormData(form);
  const messageElement = document.getElementById("cart-message");

  fetch(url, {
    method: "POST",
    headers: {
      "X-CSRFToken": formData.get("csrfmiddlewaretoken"),
    },
    body: formData,
  })
  .then(response => response.json())
  .then(data => {
  messageElement.classList.remove("hidden");

  if (data.success) {
    messageElement.textContent = data.message;
    messageElement.className = "text-green-600 mt-2";
  } else {
    messageElement.textContent = "Failed to add item to cart.";
    messageElement.className = "text-red-600 mt-2";
  }

  setTimeout(() => {
    messageElement.classList.add("hidden");
  }, 2000);
})
});
</script>

{% endblock %}

e_commerce_site/products/templates/products/product_list.html
{% extends "base.html" %}

{% block title %}Products{% endblock %}

{% block content %}
<div class="container mx-auto p-4 flex gap-6">

  <!-- Sidebar -->
  <aside class="w-1/4 p-4 bg-white rounded shadow">
    <h2 class="font-bold mb-4">Categories</h2>
    <ul class="space-y-2">
      {% for category in categories %}
        <li>
          <a
            href="{% url 'products:category_filter' category.slug %}"

            class="text-blue-600 hover:underline"
          >
            {{ category.name }}
          </a>
        </li>
      {% endfor %}
    </ul>
  </aside>

  <!-- Products -->
<main class="w-3/4">
  <div class="grid grid-cols-1 md:grid-cols-3 gap-6">

    {% for product in products %}
      <a href="{% url 'products:product_detail' product.id product.slug %}">
        <div class="bg-white p-4 rounded shadow hover:shadow-lg transition">

          {% with product.images.first as image %}
            {% if image %}
              <img
                src="{{ image.image.url }}"
                alt="{{ product.name }}"
                class="w-full h-48 object-cover mb-3 rounded"
              >
            {% endif %}
          {% endwith %}

          <h3 class="font-bold">{{ product.name }}</h3>
          <p >{{ product.description }}</p>

          {% with product.variants.first as variant %}
            {% if variant %}
              <p class="text-lg font-semibold mt-2">
                Rs {{ variant.price }}
              </p>
            {% else %}
              <p class="text-sm text-gray-500 mt-2">
                Price not available
              </p>
            {% endif %}
          {% endwith %}


        </div>
      </a>
    {% empty %}
      <p>No products found.</p>
    {% endfor %}

  </div>
</main>
  </main>

</div>
{% endblock %}